-- COMMENT
DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

-- COMMENT
USE burgers_db;

-- COMMENT
CREATE TABLE burgers (
  id INTEGER NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(100) NOT NULL,
  devoured BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
)